lb:
  image: sundeer/rancher-haproxy-vault
  ports:
    - 8200:8200
  labels:
    io.rancher.container.hostname_override: container_name

server:
  image: sundeer/docker-vault:latest
  expose:
    - 8200
  external_links:
    - consul/lb:consul
  cap_add:
    - IPC_LOCK
  command: 'server -config=/config/server.hcl'
  labels:
    io.rancher.container.hostname_override: container_name
