lb:
  image: sundeer/rancher-haproxy-vault:feature_testing
  ports:
    - 8200:8200
  labels:
    io.rancher.container.hostname_override: container_name

server-1:
  image: sundeer/docker-vault:feature_test
  expose:
    - 8200
  cap_add:
    - IPC_LOCK
  command: 'server -config=/config/server.hcl'
  external_links:
    - consul/lb:consul
  environment:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    AWS_S3_BUCKET:
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: ephemeral=false
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}

server-2:
  image: sundeer/docker-vault:feature_test
  expose:
    - 8200
  cap_add:
    - IPC_LOCK
  command: 'server -config=/config/server.hcl'
  external_links:
    - consul/lb:consul
  environment:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    AWS_S3_BUCKET:
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: ephemeral=true
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}

server-3:
  image: sundeer/docker-vault:feature_test
  expose:
    - 8200
  cap_add:
    - IPC_LOCK
  command: 'server -config=/config/server.hcl'
  external_links:
    - consul/lb:consul
  environment:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    AWS_S3_BUCKET:
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: ephemeral=true
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
