lb:
  image: sundeer/rancher-haproxy-vault:latest
  ports:
    - 8200:8200
  links:
    - server
  labels:
    io.rancher.container.hostname_override: container_name

server:
  image: sundeer/docker-vault:latest
  expose:
    - 8200
  cap_add:
    - IPC_LOCK
  command: 'server -config=/config/server.hcl'
  external_links:
    - consul/consul:consul
  environment:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    AWS_S3_BUCKET:
  labels:
    vault: true
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: vault=true
