lb:
  image: sundeer/rancher-haproxy-vault:feature_testing
  ports:
    - 8200:8200
  tty: true
  stdin_open: true
  links:
    - server_1:server_1
    - server_2:server_2
    - server_3:server_3
  labels:
    io.rancher.container.hostname_override: container_name

server_1:
  image: sundeer/docker-vault:latest
  expose:
    - 8200
  external_links:
    - consul/lb:consul
  cap_add:
    - IPC_LOCK
  command: 'server -config=/config/server.hcl'
  labels:
    io.rancher.container.hostname_override: container_name

server-2:
  image: sundeer/docker-vault:latest
  expose:
    - 8200
  external_links:
    - consul/lb:consul
  cap_add:
    - IPC_LOCK
  command: 'server -config=/config/server.hcl'
  labels:
    io.rancher.container.hostname_override: container_name

server-3:
  image: sundeer/docker-vault:latest
  expose:
    - 8200
  external_links:
    - consul/lb:consul
  cap_add:
    - IPC_LOCK
  command: 'server -config=/config/server.hcl'
  labels:
    io.rancher.container.hostname_override: container_name
