lb:
  image: sundeer/rancher-haproxy-vault:feature_testing
  ports:
    - 8200:8200
  links:
    - server-1:server-1
    - server-2:server-2
    - server-3:server-3
  labels:
    io.rancher.container.hostname_override: container_name

server-1:
  image: sundeer/docker-vault:feature_test
  expose:
    - 8200
  external_links:
    - consul/lb:consul
  cap_add:
    - IPC_LOCK
  command: 'server -config=/config/server.hcl'
  environment:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    AWS_S3_BUCKET:
  labels:
    io.rancher.container.hostname_override: container_name

server-2:
  image: sundeer/docker-vault:feature_test
  expose:
    - 8200
  external_links:
    - consul/lb:consul
  cap_add:
    - IPC_LOCK
  command: 'server -config=/config/server.hcl'
  environment:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    AWS_S3_BUCKET:
  labels:
    io.rancher.container.hostname_override: container_name

server-3:
  image: sundeer/docker-vault:feature_test
  expose:
    - 8200
  external_links:
    - consul/lb:consul
  cap_add:
    - IPC_LOCK
  command: 'server -config=/config/server.hcl'
  environment:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    AWS_S3_BUCKET:
  labels:
    io.rancher.container.hostname_override: container_name
